name: money_
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  riverpod_generator: ^3.0.0-dev.17
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  flutter_gen_runner: ^5.10.0
  
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    enabled: true
    inputs:
      - assets/colors/color.xml
    # outputs:
    #   class_name: AppColors
flutter:
  uses-material-design: true
  assets:
    - assets/images/
